//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLSOverviewWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public int RegistraionID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string RegistrationComment { get; set; }
        public int Registraion_carID { get; set; }
        public int Registraion_employeeID { get; set; }
    
        public virtual car car { get; set; }
        public virtual employee employee { get; set; }
    }
}
